config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

devise_scope :user do
  root to: 'pages#home'
end

  get :components, to: 'pages#components'
  get 'dashboard', to: 'pages#dashboard'
  get 'users_list', to: 'pages#users_list'
  get 'notifications_center', to: 'pages#notifications_center'

  resources :event_users, only: [] do
    member do
      get :confirm
      get :decline
    end
  end

  resources :events do
    #CREATING ROUTES FOR THE SIMPLE_FORM CREATION OF AN EVENT
    resources :messages, only: :create
    member do
      get :edit_what
      patch :update_what
      get :edit_address
      patch :update_address
      get :edit_when
      patch :update_when
      get :edit_friends
      patch :update_friends
      get :chatroom
    end
  end

  resources :friendships, only: :create do
    member do
      get :toggle_favorite
    end
  end # to do: rename in friendship_requests
  resources :friendship_acceptances, only: :create


  # resources :friendships, only: [] do
  #   member do
  #     post :accept
  #     get :decline
  #   end
  # end

end

app/models/event.rb
class Event < ApplicationRecord
  attr_accessor :friends, :current_latitude, :current_longitude

  belongs_to :user
  has_many :event_users, dependent: :destroy
  has_many :guests, through: :event_users, source: :user
  has_many :messages, dependent: :destroy
  # has_many_attached :photos à décommenter à la configu de Cloudinary


  # validates :emoji, presence: true
  # validates :address, presence: true
  validates :date_time, presence: true

  before_validation :set_attributes

  enum status: [:incompleted, :completed, :past]
  
  EMOJI = { anything: '🤷‍♂️', drink: '🍺', movies: '🍿', sip: '🍷', eat: '🍔', coffee: '☕️', sushis: '🍣', gym: '🏋️‍♂️', yoga: '🧘‍♀️', shop: '🛍', Rrrrr: ' 🍑', fruit: '🍌', dance: '💃', party: '🎉', basket: '🏀', surf: '🏄', run: '🏃‍♂️', football: '⚽️', code: '🤓', work: '👩‍💻', geek: '🎮', play: '🎰', bowling: '🎳', camp: '⛺️', fire: '🔥', catchup: '🥤', ski: '🎿' }

  # Geocoding
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def time_left
    seconds_diff = (Time.now - date_time).to_i.abs

    # Calculate the hours left
    hours = seconds_diff / 3600
    seconds_diff -= hours * 3600

    # Calculate the minutes left
    minutes = seconds_diff / 60

    # Calculate the seconds left
    seconds = seconds_diff % 60

    # Return a nice string that display time left format: hh:mm
    "#{hours.to_s.rjust(2, '0')}:#{minutes.to_s.rjust(2, '0')}:#{seconds.to_s.rjust(2, '0')}"
  end

  private

  def set_attributes
    # self.emoji = "🍺" if self.emoji.blank?
    # self.address = "75017, Paris" if self.address.blank?
    self.description = "Shared his plan with you" if self.status.blank?
    self.date_time = DateTime.now if self.date_time.blank?
    self.status = "incompleted" if self.status.blank?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, only: [:show, :edit_what, :update_what, :edit_address, :update_address, :edit_when, :update_when, :edit_friends, :update_friends, :destroy, :edit, :update, :chatroom]
  before_action :current_guest, only: [:edit_friends, :show]
  skip_before_action :authenticate_user!, only: [:show]

  def index
    @hosted_events = policy_scope(current_user.events)
    @invited_events = policy_scope(current_user.events_as_guest)
    @events = Event.joins(:event_users)
                   .where(events: {user_id: current_user.id})
                   .or(Event.joins(:event_users)
                            .where(event_users: {user_id: current_user.id})
                   ).distinct.order(:date_time)

    @past_events = @events.where("date_time < ?", DateTime.now.beginning_of_day)

    @ongoing_events = @events.where("date_time >= ?", DateTime.now.beginning_of_day)
                             .where("date_time < ?", DateTime.now)

    @upcoming_events = @events.where("date_time >= ?", DateTime.now.beginning_of_day)
                             .where("date_time >= ?", DateTime.now) &&
                       @events.where("date_time < ?", DateTime.now.end_of_day)
                             .where("date_time >= ?", DateTime.now)

    @later_events = @events.where("date_time >= ?", DateTime.now.end_of_day)
                             .where("date_time >= ?", DateTime.now)
    # @today_events = policy_scope()
  end

  def show
    @user_is_host = @event.user == current_user
  end

  #METHODS USED FOR THE SIMPLE_FORM:
  def edit
  end

  def update
    redirect_to event_path(@event) if @event.update(event_params)
  end

  def create
    @event = Event.new
    authorize @event
    @event.user = current_user
    @event.save
    #EventUser.create!(event: @event, user: current_user, status: "confirmed", role: "host") #If we want to add the host as the first event_uset
    redirect_to edit_what_event_path(@event)
  end

  def edit_what
  end

  def update_what
    if @event.update(event_params)
      redirect_to edit_address_event_path(@event)
    else
      render :edit_what
    end
  end

  def edit_address

  end

  def update_address
    if @event.update(event_params)
      redirect_to edit_when_event_path(@event)
    else
      render :edit_address
    end
  end

  def edit_when
  end

  def update_when
    if @event.update(event_params)
      redirect_to edit_friends_event_path(@event)
    else
      render :edit_when
    end
  end

  def edit_friends
    # @friends = current_user.friendships.where(status: "approved")
    @friends = current_user.friendships
                           .where(status: "approved")
                           .order(favorite: :desc)
                           .map { |friendship| User.find(friendship.friend_id) }
  end

  def update_friends
    @event.event_users.destroy_all
    params[:event][:friends].each do |user_id|
      EventUser.create(event: @event, user_id: user_id)
    end
    @event.update(open: params.dig(:event, :open) == '1' ? true : false)
    @event.completed!
    redirect_to root_path
  end

  def destroy
    authorize @event
    @event.destroy
    redirect_to root_path
  end

  def chatroom
    @message = Message.new
  end

  private

  def find_event
    @event = Event.find(params[:id])
    authorize @event
  end

  def event_params
    strong_params = params.require(:event).permit(:emoji, :address, :date_time, :status)
    strong_params[:emoji] = Event::EMOJI[strong_params[:emoji].to_sym] if strong_params[:emoji]
    strong_params
  end

  def current_guest
    @current_guest = @event.event_users.find_by(user: current_user)
  end
end

app/views/events/_card.html.erb
<div class="d-flex w-100">
  <%= link_to event_path(event), class: 'w-100' do %>
    <div class="event-card">
      <div class="content-center-vertical">
        <%= cl_image_tag event.user.avatar.key, class: 'avatar-small' %>
      </div>
      <div class="description-box-b mx-2">
        <div class="name-emoji-time d-inline-flex">
          <div class="text-emoji-box d-flex">
            <p class="text-white mr-2"><%= event.user.first_name %></p>
            <h3 class="emoji-small"><%= event.emoji %></h3>
          </div>
          <div class= text-timer-small>
            <p>
              <% if event.date_time >= DateTime.now.beginning_of_day && event.date_time < DateTime.now %>
                <%= "started #{event.time_left} min ago" %>
              <% elsif event.date_time >= DateTime.now.beginning_of_day && event.date_time >= DateTime.now %>
                <%= "starts at #{event.time_left}" %>
              <% else %>
                <%= "#{((Time.now - event.date_time)/86400).to_i}days ago" %>
              <% end %>
            </p>
          </div>
        </div>
        <div class="description-small">
          <p><%= event.description %></p>
        </div>
      </div>
    </div>
  <% end %>

  <% if event.user == current_user || event.event_users.find_by(user: current_user).status == "confirmed" %>
    <div class="ml-2">
      <%= link_to chatroom_event_path(event) do %>
        <p class="conversation-icon">💬</p>
      <% end %>
    </div>
  <% elsif event.event_users.find_by(user: current_user).status == "declined"%>
    <div class="ml-2">
      <p class="conversation-icon">❌</p>
    </div>
  <% else %>
  <div class="ml-2">
    <p class="conversation-icon">🤷‍♂️</p>
  </div>
  <% end %>
</div>

app/views/events/_emoji_label.html.erb
  <div class="emoji-box">
    <%= emoji[0] %>
    <p> <%= emoji[1] %></p>
  </div>

app/views/events/_event_users_list.html.erb
<div class="show-friends-container">
  <div class="show-friends-box">
    <% event_users.each do |event_user| %>
      <div class="col-4">
        <div class="show-emoji-friend-box">
          <div id="icone-relative"><%= EventUser::EMOJI_STATUS[event_user.status.to_sym] %></div>
          <%= cl_image_tag event_user.user.avatar.key, class: "avatar-profile" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/_info_event_show_box.html.erb
<% is_owner = event.user == current_user %>

<div class="event-show-details-box event-show-details-box-modal">
  <div>
    <%= cl_image_tag event.user.avatar.key, class: "avatar-profile" %>
  </div>

  <div class="event-show-address-hour-box">
    <div>
      <div>
        <% if event.date_time == DateTime.now %>
          <p><%= "🗓 #{event.date_time.strftime('Today at %H:%M')}" %></p>
        <% else %>
          <p><%= "🗓 #{event.date_time.strftime('%a %d at %H:%M')}" %></p>
        <% end %>
      </div>
    </div>

    <div>
      <% if event.address.length > 40 %>
        <p id="event-address"><%= "📍 #{event.address.first(30)}...#{event.address.last(15)}" %></p>
      <% else %>
        <p id="event-address"><%= "📍 #{event.address}" %></p>
      <% end %>
    </div>
  </div>

  <div class="mt-2">
    <%= link_to "💬", chatroom_event_path(event), class: "conversation-icon outline-none" %>
  </div>
</div>








<%
=begin %>

<% is_owner = event.user == current_user %>

<div class="infos-event-show-box">
  <%= cl_image_tag event.user.avatar.key, class: "avatar-profile" %>

  <div class= "box-infos">

    <div class="box-address">
      <% if event.address.length > 40 %>
        <p id="event-address"><%= "#{event.address.first(30)}...#{event.address.last(15)}" %></p>
      <% else %>
        <p id="event-address"><%= event.address %></p>
      <% end %>
    </div>

    <div class="box-date">
      <% if event.date_time == DateTime.now %>
        <p><%= event.date_time.strftime("Today at %H:%M") %></p>
      <% else %>
        <p><%= event.date_time.strftime("%a %d at %H:%M") %></p>
      <% end %>
    </div>

    <div class="emoji-chat">
      <%= link_to "💬", chatroom_event_path(event), class: "outline-none" %>
    </div>

  </div>
</div>

<%
=end %>

app/views/events/_user_label.html.erb
<!-- <div class="avatar-list"> -->
  <div class=" avatar-box avatar-friend-selected m-1">

    <%= cl_image_tag user.avatar.key, class: 'avatar-friend' %>
    <% if current_user.friendships.where(favorite: true, friend: user).exists? %>
      <i class="fas fa-star text-linear-gradient" id="favorite-star"></i>
    <% end %>
  </div>
<!-- </div> -->

app/views/events/chatroom.html.erb
<div class="content-container">

  <div class="pages-title">
    <div class="d-flex align-items-center justify-content-center">
      <div class="back-button-title">
        <%= link_to event_path(@event) do %>
          <i class="fas fa-chevron-left text-white"></i>
        <% end %>
      </div>

      <div class="box-title">
        <h1>
          <%= "The #{Event::EMOJI.find { |k, v| v == @event.emoji }.first } #{@event.emoji} channel" %>
        </h1>
      </div>

      <div class="empty-box-title"></div>
    </div>

    <p>What! You didn't invite the Pong team?</p>
  </div>

  <div id="messages" data-event-id="<%= @event.id %>" data-user-id="<%= current_user.id %>">
    <% @event.messages.each do |message| %>
      <%= render message, is_author: message.user == current_user %>
    <% end %>
  </div>

  <%= simple_form_for [ @event, @message ], html: {class: "input-message"}, remote: true do |f| %>
    <div class="background-grey-chat">
      <%= f.input :content, as: :string, label: false, placeholder: "#{current_user.first_name}, type your message here..." %>
      <button class="paper-plane" type="submit"><i class="far fa-paper-plane"></i></button>
    </div>
  <% end %>
</div>

app/views/events/edit_address.html.erb
<div class="content-container">

  <div class="pages-title">
    <div class="d-flex align-items-center justify-content-center">
      <div class="back-button-title">
        <%= link_to edit_what_event_path(@event) do %>
          <i class="fas fa-chevron-left text-white"></i>
        <% end %>
      </div>

      <div class="box-title">
        <h1>Where?</h1>
      </div>

      <div class="empty-box-title"></div>
    </div>

    <p>Choose your actual location or type an address.</p>
  </div>

  <div class="mt-3">
    <%= simple_form_for @event, url: update_address_event_path(@event) do |f| %>
      <%= f.input :address, placeholder: "16 villa Gaudelet, 75010 Paris" %> <%# dont forget to get the current location + add geocoder and lat & lgt %>
      <%#= f.input :current_latitude, wrapper_html: {class: 'd-none'} %>
      <%#= f.input :current_longitude, wrapper_html: {class: 'd-none'} %>
      <div id="address_coordinates" class="text-white d-flex justify-content-center"></div>
      <div class="fixed-bottom btn-margin-bottom">
        <%= f.button :submit, "Next 👉", class: "button-next" %>
      </div>
    <% end %>
  </div>
</div>

<div id="mapEventCreation"
  style="width: 100vw; height: 100vh;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/events/edit_friends.html.erb
<div class="content-container">

  <div class="pages-title">
    <div class="d-flex align-items-center justify-content-center">
      <div class="back-button-title">
        <%= link_to edit_when_event_path(@event) do %>
          <i class="fas fa-chevron-left text-white"></i>
        <% end %>
      </div>

      <div class="box-title">
        <h1 id="event-pick-friends">Pick your friends!</h1>
      </div>

      <div class="empty-box-title"></div>
    </div>

    <p>Only them will know about your plan.</p>
  </div>

  <div class= "toggle-text mb-2 mt-4">
    <p>Friends can join with friends:</p>

    <label class="switch">
      <input type="checkbox" checked>
      <span class="slider round"></span>
    </label>
  </div>

  <p class ="border-grey">Search group or friends 🔎</p>

  <%= simple_form_for @event, url: update_friends_event_path(@event) do |f| %>
    <%= f.input :friends,
      as: :check_boxes,
      label_method: lambda { |user| render "events/user_label", user: user },
      collection: @friends,
      checked: @event.guests.pluck(:id),
      input_html: {class: 'd-none radio-btn'},
      item_wrapper_class: :radio,
      # include_blank: false,
      include_hidden: false %>
    <%= f.input :open, input_html: { value: '1', id:'toggle-value', class: 'd-none' } %>

    <div class="box-btn-share-cancel-plan d-none">
      <%= link_to "Cancel plan", event_path(@event), method: :delete, data: { confirm: "Are you sure?" }, class: "mb-2 btn-cancel-plan" %>
        <br>
        <br>
      <div class="background-grey fixed-bottom">
        <%= f.button :submit, "💥 Share my plan 💥", class: "d-none", id: "edit-friends-submit"%>
        <%#= link_to "", event_path(@event), id: "confirm-link", class: "hidden" %>
        <%= link_to "Share my plan 💥", "", id: "share-my-plan", class: 'button-next mb-3' %>
      </div>
    </div>
  <% end %>

  </div>
</div>

app/views/events/edit_what.html.erb
<div class="content-container">

  <div>
    <div class="form-event-title">
        <%# POURQUOI LE DELETE RENVOIE VERS ROOT? %>
        <%= link_to event_path(@event), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fas fa-chevron-left"></i>
      <% end %>
    </div>

    <div class="text-center">
      <h1>What are you up to?</h1>
      <p>Choose wisely... we decline all responsability if the situation gets out of control.</p>
    </div>
  </div>

  <%= simple_form_for @event, url: update_what_event_path(@event) do |f| %>
    <%#= f.input :emoji, as: :radio_buttons,
    collection: Event::EMOJI %>

    <%= f.input :emoji,
      as: :radio_buttons,
      wrapper_tag: :fieldset,
      label_method: lambda { |emoji| render "events/emoji_label", emoji: emoji },
      collection: Event::EMOJI.to_a.map(&:reverse),
      input_html: { multiple: false },
      item_wrapper_class: :radio,
      # selected: Event::EMOJI.first,
      include_hidden: false %>

    <div class="background-grey fixed-bottom">
      <%= f.submit "Next 👉", class: "button-next d-none" %>
    </div>
  <% end %>
</div>

app/views/events/edit_when.html.erb
<div class="content-container">

  <div class="pages-title">
    <div class="d-flex align-items-center justify-content-center">
      <div class="back-button-title">
        <%= link_to edit_address_event_path(@event) do %>
          <i class="fas fa-chevron-left text-white"></i>
        <% end %>
      </div>

      <div class="box-title">
        <h1>When?</h1>
      </div>

      <div class="empty-box-title"></div>
    </div>

    <p>Adjust day and time(ish) of the begining of your plan.</p>
  </div>

  <div class="tab-centered">
    <ul class="toggle-nav nav nav-pills mb-3 d-flex justify-content-center" id="pills-tab" role="tablist">
      <li class="nav-item left-tab" role="presentation">
        <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Today</a>
      </li>
      <li class="nav-item right-tab" role="presentation">
        <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Later</a>
      </li>
    </ul>
  </div>

  <br>

  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
        <h1 class="text-today d-none">Today</h1>
      <div class= "time-big">
        <div class="time-scroll-box-hours d-flex flex-column mt-2 mr-3 align-items-center">
          <h1 id="time-hour-more" class=""><i class="fas fa-plus-circle"></i></h1>
          <h1 id="time-hour-less" class="pt-2"><i class="fas fa-minus-circle"></i></h1>
        </div>
        <div class="d-flex align-items-center">
          <h1 id="time-hour" class="text-linear-gradient mr-2"></h1>
          <h1 class="text-linear-gradient"> : </h1>
          <h1 id="time-min" class="text-linear-gradient ml-2"></h1>
        </div>
        <div class="time-scroll-box-mins d-flex flex-column mt-2 ml-3 align-items-center">
          <h1 id="time-min-more"><i class="fas fa-plus-circle"></i></i></h1>
          <h1 id="time-min-less" class="pt-2"><i class="fas fa-minus-circle"></i></h1>
        </div>
      </div>
      <br>
      <br>

      <%= simple_form_for @event, url: update_when_event_path(@event) do |f| %>

        <%= f.input :date_time, as: :time, label: false, class: 'input-hidden' %>
        <%= f.button :submit, "Next 👉", class: "button-next fixed-bottom btn-margin-bottom" %>
        <%#= f.input :date_time, as: :time, label: false %>
        <%#= f.button :submit, "Next 👉", class: "button-next fixed-bottom btn-margin-bottom" %>

      <% end %>
    </div>
    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
      <%= simple_form_for @event, url: update_when_event_path(@event) do |f| %>
        <%= f.input :date_time, as: :string, required: false, input_html: {class: "datepicker"} %>
        <!-- <div class="fixed-bottom"> -->
          <%= f.button :submit, "Next 👉", class: "button-next fixed-bottom btn-margin-bottom" %>
        <!-- </div> -->
      <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="content-container">

  <div class="pages-title">
    <div class="d-flex align-items-center justify-content-center">
      <div class="back-button-title">
        <%= link_to events_path do %>
          <i class="fas fa-chevron-left text-white"></i>
        <% end %>
      </div>

      <div class="box-title">
        <h1 id="event-show-title">
          <%= "#{@event.emoji} Let's #{Event::EMOJI.find { |k, v| v == @event.emoji }.first }!" %>
        </h1>
      </div>

      <div class="empty-box-title"></div>
    </div>

    <p>Seems awesome, let's have fun guys.</p>
  </div>

  <%= render "events/info_event_show_box", event: @event %>

  <div class="event-show-timer">
    <div>
      <%# L'event est en cours et ça fait moins de 8h qu'il a débuté %>
      <% if Time.now > @event.date_time && Time.now < @event.date_time + (8 * 3600) %>
        <h4>
          <%= "The event is ongoing, enjoy it folks!" %>
        </h4>

      <%# L'event commence dans 1 jour ou plus  %>
      <% elsif Time.now + 86400 < @event.date_time %>
        <h4>
          <%= " #{((@event.date_time - Time.now) / 84600).round} day(s) before the beginning of the event" %>
        </h4>

      <%# L'event commence dans moins de 24h %>
      <% elsif Time.now < @event.date_time %>
        <h3 class="timer" data-event-date='<%= @event.date_time %>'>
        </h3>

      <%# L'event est terminé (8h après son début) %>
      <% else %>
        <h4>
          <%= "The event is now finished..." %>
        </h4>
      <% end %>
    </div>
  </div>

  <%# DISPLAY FRIENDS FOR WHO THEY'RE JOINING THE EVENT %>

  <%# IF CURRENT_USER IS THE EVENT HOST %>
  <%# tip: '&' permet de refacto -> current_user && current_user.user_is_host?(@event) %>
  <% if current_user&.user_is_host?(@event) %>

    <%= render "events/event_users_list.html.erb", event_users: @event.event_users.order_by_status %>

    <div class="show-buttons-container">
      <div class="show-buttons-edit-invitations">
        <%= link_to "Edit plan ✍️", edit_event_path(@event), class: "button-next mb-2" %>

        <% if policy(@event).destroy? %>
          <%= link_to "Invitations 📨", edit_friends_event_path(@event), class: "button-next mb-2" if policy(@event).edit_friends? %>
      </div>
      <div class="show-buttons-share-delete">
          <p id="share-link">🔗</p>
          <%= link_to "🗑", event_path(@event), method: :delete, data: { confirm: "Are you sure to delete your event?" }, class: "" %>
      </div>
        <% end %>
    </div>

  <%# IF CURRENT_USER IS A PARTNER OR A VISITOR %>
  <% else  %>

    <% if current_user && @event.event_users.find_by(user: current_user).status == "confirmed" %>
      <%#= link_to "Share link", event_path(@event), class: "button-next" if @event.event_users.find_by(user: current_user).role == "partner" %>
      <%#= link_to "Invite a friend", event_path(@event), class: "button-next" if @event.event_users.find_by(user: current_user).role == "partner" %>
      <%= render "events/event_users_list.html.erb", event_users: @event.event_users.order_by_status %>
      <%= link_to "Change my mind 😱", decline_event_user_path(@event.event_users.find_by(user: current_user)), data: { confirm: "Are you sure to decline the event?" }, class: "button-next mb-4 mt-5" %>

    <% elsif current_user && @event.event_users.find_by(user: current_user).status == "pending" %>
      <%= render "events/event_users_list.html.erb", event_users: @event.event_users.order_by_status %>
      <%= link_to "Join 👊", confirm_event_user_path(@event.event_users.find_by(user: current_user)), class: "button-next btn-join mb-2 mt-5" %>
      <%= link_to "Plouf 💦", decline_event_user_path(@event.event_users.find_by(user: current_user)), data: { confirm: "Are you sure to decline the event?" }, class: "button-next btn-plouf mb-4" %>

    <% elsif current_user && @event.event_users.find_by(user: current_user).status == "decline" %>
      <%= render "events/event_users_list.html.erb", event_users: @event.event_users.order_by_status %>
      <%= link_to "Change my mind", confirm_event_user_path(@event.event_users.find_by(user: current_user)), class: "button-next mb-4 mt-5" %>
    <% else %>
       <%= link_to "Sign up to answer", new_user_session_path, class: "button-next mb-4 mt-5" %>
    <% end %>
  <% end  %>
</div>


<%
=begin %>

<div class="content-container">

  <%= link_to chatroom_event_path(@event) do %>
    <h1 id="event-show-title">
      <%= "#{@event.emoji} Let's #{Event::EMOJI.find { |k, v| v == @event.emoji }.first } together!" %>
    </h1>
  <% end %>

  <%= render "events/info_event_show_box", event: @event %>
  <br>

  <div class="event-show-timer">
    <div id="timer">

        <%= @event.time_left %>

    </div>
    <h6>Before the beginning of the event</h6>
  </div>

  <div class="event-description-box">
    <p class="light-p">
      <%= "#{@event.description}"%>
    </p>
  </div>

  <%# DISPLAY FRIENDS FOR WHO THEY'RE JOINING THE EVENT %>

  <%# IF CURRENT_USER IS THE EVENT HOST %>
  <% if @user_is_host %>
    <div class="manage-event-buttons">
      <%= link_to "Share link", event_path, class: "button-medium" %>
      <%= link_to "Invite", edit_friends_event_path, class: "button-medium" if policy(@event).edit_friends? %>
    </div>

    <%= render "events/event_users_list.html.erb", event_users: @event.event_users.order_by_status %>

    <div class="container-buttons-top-bottom">
      <%= link_to "Edit plan", edit_event_path, class: "button-next mb-2" %>
      <% if policy(@event).destroy? %>
        <%= link_to "Delete my plan", event_path(@event), method: :delete, data: { confirm: "Are you sure?" }, class: "button-next" %>
      <% end %>
    </div>


  <%# IF CURRENT_USER IS A PARTNER OR A VISITOR %>
  <% else  %>

    <% if @event.event_users.find_by(user: current_user).confirmed? %>
      <div class="manage-event-buttons">
        <%# le statut du user doit passer en "declined" %>
        <%= link_to "Change answer", decline_event_user_path(@current_guest), class: "button-next mr-1" %>
        <%# le lien de l'event doit être copié dans le presse papier du current user pour qu'il puisse partager" %>
        <%= link_to "Invite a friend", @event_path, class: "button-next ml-1" if @current_guest.role == "partner" %>
      </div>

    <% elsif @current_guest.status == "pending" %>
      <%= render "events/event_users_list.html.erb", event_users: @event.event_users.order_by_status %>

      <%= link_to "Join 👊", confirm_event_user_path(@current_guest), class: "button-next btn-join mb-2" %>
      <%= link_to "Plouf 💦", decline_event_user_path(@current_guest), class: "button-next btn-plouf" %>

    <% else %>
      <%# le statut de l'event doit passer en "declined" et pas en "past"  %>
    <% end %>
  <% end  %>
</div>

<%
=end %>