config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

devise_scope :user do
  root to: 'pages#home'
end

  get :components, to: 'pages#components'
  get 'dashboard', to: 'pages#dashboard'
  get 'users_list', to: 'pages#users_list'
  get 'notifications_center', to: 'pages#notifications_center'

  resources :event_users, only: [] do
    member do
      get :confirm
      get :decline
    end
  end

  resources :events do
    #CREATING ROUTES FOR THE SIMPLE_FORM CREATION OF AN EVENT
    resources :messages, only: :create
    member do
      get :edit_what
      patch :update_what
      get :edit_address
      patch :update_address
      get :edit_when
      patch :update_when
      get :edit_friends
      patch :update_friends
      get :chatroom
    end
  end

  resources :friendships, only: :create do
    member do
      get :toggle_favorite
    end
  end # to do: rename in friendship_requests
  resources :friendship_acceptances, only: :create


  # resources :friendships, only: [] do
  #   member do
  #     post :accept
  #     get :decline
  #   end
  # end

end

app/views/pages/_info_window.html.erb
<div class="window-top"></div>

<div class="content-container">

  <div class="pages-title pages-title-modal">
    <div class="d-flex align-items-center justify-content-center">
      <div class="back-button-title">
        <%= link_to events_path do %>
          <i class="fas fa-chevron-left text-white"></i>
        <% end %>
      </div>

      <div class="box-title">
        <h1 id="event-show-title">
          <%= "#{event.emoji} Let's #{Event::EMOJI.find { |k, v| v == event.emoji }.first }!" %>
        </h1>
      </div>

      <div class="empty-box-title"></div>
    </div>

    <p>Seems awesome, let's have fun guys.</p>
  </div>

  <%= render "events/info_event_show_box", event: event %>

  <div class="event-show-timer event-show-timer-modal">
    <div>
      <%# L'event est en cours et ça fait moins de 8h qu'il a débuté %>
      <% if Time.now > event.date_time && Time.now < event.date_time + (8 * 3600) %>
        <h4>
          <%= "The event is ongoing, enjoy it folks!" %>
        </h4>

      <%# L'event commence dans 1 jour ou plus  %>
      <% elsif Time.now + 86400 < event.date_time %>
        <h4>
          <%= " #{((event.date_time - Time.now) / 84600).round} day(s) before the beginning of the event" %>
        </h4>

      <%# L'event commence dans moins de 24h %>
      <% elsif Time.now < event.date_time %>
        <h3 class="timer" data-event-date='<%= event.date_time %>'>
        </h3>

      <%# L'event est terminé (8h après son début) %>
      <% else %>
        <h4>
          <%= "The event is now finished..." %>
        </h4>
      <% end %>
    </div>
  </div>

  <div id="url-show-hidden" class="d-none"><%= event.id %></div>

  <%# DISPLAY FRIENDS FOR WHO THEY'RE JOINING THE EVENT %>

  <%# IF CURRENT_USER IS THE EVENT HOST %>
  <%# tip: '&' permet de refacto -> current_user && current_user.user_is_host?(event) %>
  <% if current_user&.user_is_host?(event) %>

    <%= render "events/event_users_list.html.erb", event_users: event.event_users.order_by_status %>

    <div class="show-buttons-container">
      <div class="show-buttons-edit-invitations">
        <%= link_to "Edit plan ✍️", edit_event_path(event), class: "button-next mb-2" %>

        <% if policy(event).destroy? %>
          <%= link_to "Invitations 📨", edit_friends_event_path(event), class: "button-next mb-2" if policy(event).edit_friends? %>
      </div>
      <div class="show-buttons-share-delete show-buttons-share-delete-modal">
          <p id="share-link-modal">🔗</p>
          <%= link_to "🗑", event_path(event), method: :delete, data: { confirm: "Are you sure to delete your event?" }, class: "" %>
      </div>
        <% end %>
    </div>

  <%# IF CURRENT_USER IS A PARTNER OR A VISITOR %>
  <% else  %>

    <% if current_user && event.event_users.find_by(user: current_user).status == "confirmed" %>
      <%#= link_to "Share link", event_path(event), class: "button-next" if event.event_users.find_by(user: current_user).role == "partner" %>
      <%#= link_to "Invite a friend", event_path(event), class: "button-next" if event.event_users.find_by(user: current_user).role == "partner" %>
      <%= render "events/event_users_list.html.erb", event_users: event.event_users.order_by_status %>
      <%= link_to "Change my mind 😱", decline_event_user_path(event.event_users.find_by(user: current_user)), data: { confirm: "Are you sure to decline the event?" }, class: "button-next mb-4 mt-5" %>

    <% elsif current_user && event.event_users.find_by(user: current_user).status == "pending" %>
      <%= render "events/event_users_list.html.erb", event_users: event.event_users.order_by_status %>
      <%= link_to "Join 👊", confirm_event_user_path(event.event_users.find_by(user: current_user)), class: "button-next btn-join mb-2 mt-5" %>
      <%= link_to "Plouf 💦", decline_event_user_path(event.event_users.find_by(user: current_user)), data: { confirm: "Are you sure to decline the event?" }, class: "button-next btn-plouf mb-4" %>

    <% else %>
      <%= render "events/event_users_list.html.erb", event_users: event.event_users.order_by_status %>
      <%= link_to "Change my mind", confirm_event_user_path(event.event_users.find_by(user: current_user)), class: "button-next mb-4 mt-5" %>
    <% end %>
  <% end  %>
</div>







































































































<%# -------------------------------- %>
<%
=begin %>

  <div class="window-top">
  </div>
<div class="content-container">

  <h1 id="event-show-title">
    <%= "#{event.emoji} Let's #{Event::EMOJI.find { |k, v| v == event.emoji }.first } together!" %>
  </h1>

  <div class="infos-event-show-box">
    <%= cl_image_tag event.user.avatar.key, class: "avatar-profile secure: true" %>

    <div class= "box-infos">

      <div class="box-address">
        <% if event.address.length > 40 %>
          <p id="event-address"><%= "#{event.address.first(30)}...#{event.address.last(15)}" %></p>
        <% else %>
          <p id="event-address"><%= event.address %></p>
        <% end %>
      </div>

      <div class="box-date">
        <% if event.date_time == DateTime.now %>
          <p><%= event.date_time.strftime("Today at %H:%M") %></p>
        <% else %>
          <p><%= event.date_time.strftime("%a %d at %H:%M") %></p>
        <% end %>
      </div>

      <div id="emoji-chat-info-window">
        <%= link_to "💬", chatroom_event_path(event)  %>
      </div>

    </div>
  </div>

  <div class="event-show-timer">
    <div>
      <% if Time.now < event.date_time %>
        <div class="timer" id="timer-show">
          <%= event.time_left %>
        </div>
        <h6>Before the beginning of the event</h6>
      <% else %>
        <h1>
          <%= "It's #{event.emoji} time! " %>
        </h1>
      <% end %>
    </div>
  </div>

  <div class="event-description-box">
    <p class="light-p">
      <%= "#{event.description}"%>
    </p>
  </div>

  <%#=  si le mec qui arrive sur la show est host j'affiche event parti %>

  <%# DISPLAY FRIENDS FOR WHO THEY'RE JOINING THE EVENT %>

  <%# IF CURRENT_USER IS THE EVENT HOST %>
  <% if current_user.user_is_host?(event) %>

    <%= render "events/event_users_list.html.erb", event_users: event.event_users.order_by_status %>

    <div class="container-buttons-top-bottom">
      <%= link_to "✍️ Edit plan", edit_event_path(event), class: "button-next mb-2" %>

      <% if policy(event).destroy? %>
        <%= link_to "Manage invitations", edit_friends_event_path(event), class: "button-next mb-2" if policy(event).edit_friends? %>
        <%= link_to "Share event", root_path, class: "button-next btn-delete-grey mb-2" %>
        <%= link_to "Delete my plan", event_path(event), method: :delete, data: { confirm: "Are you sure?" }, class: "button-next btn-delete-grey mb-2" %>
      <% end %>
    </div>

  <%# IF CURRENT_USER IS A PARTNER OR A VISITOR %>
  <% else  %>

    <% if event.event_users.find_by(user: current_user).status == "confirmed" %>
      <%= link_to "Share link", event_path(event), class: "button-next" if event.event_users.find_by(user: current_user).role == "partner" %>
      <%= link_to "Invite a friend", event_path(event), class: "button-next" if event.event_users.find_by(user: current_user).role == "partner" %>
      <%= render "events/event_users_list.html.erb", event_users: event.event_users.order_by_status %>
      <%= link_to "Change my mind 😱", decline_event_user_path(event.event_users.find_by(user: current_user)), data: { confirm: "Are you sure to decline the event?" }, class: "button-next mb-2" %>

    <% elsif event.event_users.find_by(user: current_user).status == "pending" %>
      <%= render "events/event_users_list.html.erb", event_users: event.event_users.order_by_status %>
      <%= link_to "Join 👊", confirm_event_user_path(event.event_users.find_by(user: current_user)), class: "button-next btn-join mb-2" %>
      <%= link_to "Plouf 💦", decline_event_user_path(event.event_users.find_by(user: current_user)), data: { confirm: "Are you sure to decline the event?" }, class: "button-next btn-plouf" %>

    <% else %>
      <%= render "events/event_users_list.html.erb", event_users: event.event_users.order_by_status %>
      <%= link_to "Change my mind 😱", confirm_event_user_path(event.event_users.find_by(user: current_user)), class: "button-next mb-2" %>
    <% end %>
  <% end  %>
</div>

<%
=end %>

<%# ------------------------------------------- %>


























<%
=begin %>

<!-- Mapbox, app/views/flats/_info_window.html.erb -->
<div class="content-container">

  <h1 id="event-show-title">
    <%= " #{event.emoji} Let's #{Event::EMOJI.find { |k, v| v == event.emoji }.first } together!" %>
  </h1>

  <%= render "events/info_event_show_box", event: event %>

  <div class="event-show-timer">
    <div id="timer">
      <p>
        <%= event.time_left %>
      </p>
    </div>
    <h6>Before the beginning of the event</h6>
  </div>

  <div class="event-description-box">
    <p class="light-p">
      <%= "#{event.description}"%>
    </p>
  </div>

  <%#=  si le mec qui arrive sur la show est host j'affiche event parti %>

  <%# DISPLAY FRIENDS FOR WHO THEY'RE JOINING THE EVENT %>

  <%# IF CURRENT_USER IS THE EVENT HOST %>
  <% if current_user.user_is_host?(event) %>

    <%= render "events/event_users_list.html.erb", event_users: event.event_users.order_by_status %>
    <%#= link_to "Copy event link", event_path, class: "gradient-box" %>
    <%#= link_to "Manage invitations", edit_friends_event_path, class: "button-medium" if policy(event).edit_friends? %>
    <div class="manage-event-buttons">
      <% if policy(event).destroy? %>
        <%= link_to "Delete plan", event_path(event), method: :delete, data: { confirm: "Are you sure?" }, class: "button-medium" %>
      <% end %>
      <%#= link_to "Edit plan", event_path, class: "button-medium" %>
    </div>

  <%# IF CURRENT_USER IS A PARTNER OR A VISITOR %>
  <% end  %>
</div>

  <% else  %>
    <% if event.event_users.find_by(user: current_user).confirmed? %>
      <div class="manage-event-buttons">
        <%= link_to "Change answer", event_path, class: "btn btn-outline-primary" %>
        <%= link_to "Invite a friend", event_path, class: "btn btn-outline-secondary" if @current_guest.role == "partner" %>
      </div>

    <% elsif @current_guest.status == "pending" %>
      <div class="manage-event-buttons">
        <%= link_to "Decline", decline_event_user_path(@current_guest), class: "button-medium" %>
        <%= link_to "Confirm", confirm_event_user_path(@current_guest), class: "button-medium" %>
      </div>

    <% else %>
      <%# le statut de l'event doit passer en "declined" et pas en "past"  %>
    <% end %>







----------------------------- PREVIOUS POPUP VERSION -----------------------------
<h2><%= event.emoji %></h2>
<p>Address: <%= event.address %></p>

<p>Date: <%= event.date_time %></p>
<br>
<%= link_to "more", event_path(event), class: "button-next-small" %>
<br>
<br>
<p>Friends participating:</p>

   <% event.event_users.each do |event_user| %>
      <% if event_user.status == "confirmed" %>
        <p>
          <%= cl_image_tag event_user.user.avatar.key, class: "avatar-profile" %>
          <%= event_user.user.first_name %>
        </p>
      <% end %>
    <% end %>

<%
=end %>

app/views/pages/components.html.erb
<%# PAGES TITLE %>

<div class="pages-title">
  <div class="d-flex align-items-center justify-content-center">
    <div class="back-button-title">
      <%= link_to root_path do %>
        <i class="fas fa-chevron-left text-white"></i>
      <% end %>
    </div>

    <div class="box-title">
      <h1>Write my title here</h1>
    </div>

    <div class="empty-box-title"></div>
  </div>

  <p>This is the punchline of the page</p>
</div>

<%# ----------  %>


<br>

<div class="background-grey">
  <%= link_to "Next 👉" , root_path, class: "button-next" %>
</div>

<div class="container">
  <h1>Title 1</h1>
  <p>Paragraph</p>

  <br>

  <div class="gradient-box">
    <%= link_to "Share my plan" , root_path, class: "text-button" %>
  </div>

  <br>

  <br>

  <div class="emoji-list">
    <div class="emoji-box m-1">
      <p>🍺</p>
      <span class="text-white emoji-text">Beer</span>
    </div>
    <div class="emoji-box m-1">
      <p>🍺</p>
      <span class="text-white emoji-text">Beer</span>
    </div>
    <div class="emoji-box m-1">
      <p>🍺</p>
      <span class="text-white emoji-text">Beer</span>
    </div>
    <div class="emoji-box m-1">
      <p>🍺</p>
      <span class="text-white emoji-text">Beer</span>
    </div>
    <div class="emoji-box m-1">
      <p>🍺</p>
      <span class="text-white emoji-text">Beer</span>
    </div>
    <div class="emoji-box gradient-bordered m-1">
      <p>🍺</p>
      <span class="text-white emoji-text">Beer</span>
    </div>
  </div>

  <div class="avatar-list">
    <div class=" avatar-box avatar-friend-selected m-1">
      <img src="https://avatars3.githubusercontent.com/u/67843990?v=4" alt="Raph" class="avatar-friend">
    </div>
    <div class="avatar-box avatar-friend-selected m-1">
      <img src="https://avatars3.githubusercontent.com/u/67843990?v=4" alt="Raph" class="avatar-friend">
      </div>
    <div class="avatar-box avatar-friend-selected m-1">
      <img src="https://avatars3.githubusercontent.com/u/67843990?v=4" alt="Raph" class="avatar-friend">
    </div>
  </div>

<div class="avatar-profile-selected">
  <img src="https://avatars3.githubusercontent.com/u/67843990?v=4" alt="Raph" class="avatar-profile">
</div>

<!-- <div class="">
  <img src="https://avatars3.githubusercontent.com/u/67843990?v=4" alt="Raph" class="avatar-big">
</div>

<div class="avatar-big-bordered">

</div>
 -->

</div>
<br>

app/views/pages/dashboard.html.erb
<div class="content-container">

  <div class="pages-title">
    <div class="d-flex align-items-center justify-content-center">
      <div class="back-button-title">
        <%= link_to root_path do %>
          <i class="fas fa-chevron-left text-white"></i>
        <% end %>
      </div>

      <div class="box-title">
        <h1>Your friends</h1>
      </div>

      <div class="empty-box-title">
        <% if current_user.facebook_picture_url %>
          <%= image_tag current_user.facebook_picture_url, class: "avatar-friend", "data-toggle" => "dropdown" %>
        <% elsif current_user.avatar.attached? %>
          <%= cl_image_tag current_user.avatar.key, class: "avatar-friend" %>
        <% else %>
          <%= image_tag "http://placehold.it/30x30", class: "avatar-friend", alt: "alttext" %>
        <% end %>
      </div>
    </div>

    <p>Partners at any time. How beautiful they are.</p>
  </div>

<%
=begin %>

  <div class="dashboard-title">
    <div class="form-event-title">
      <%= link_to root_path do %>
        <i class="fas fa-chevron-left"></i>
      <% end %>
    </div>
    <h1 class="title-center"><%= "Friends" %></h1>
      <% if current_user.facebook_picture_url %>
        <%= image_tag current_user.facebook_picture_url, class: "avatar-friend", "data-toggle" => "dropdown" %>
      <% elsif current_user.avatar.attached? %>
        <%= cl_image_tag current_user.avatar.key, class: "avatar-friend" %>
      <% else %>
        <%= image_tag "http://placehold.it/30x30", class: "avatar-friend", alt: "alttext" %>
      <% end %>
  </div>
<%
=end %>

  <%# avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
  <%#= image_tag avatar_url, class: "avatar-home-page", "data-toggle" => "dropdown" %>





<%
=begin %>
      <% if current_user.facebook_picture_url %>
        <%= image_tag current_user.facebook_picture_url, class: "avatar-friend", "data-toggle" => "dropdown" %>
      <% elsif current_user.avatar.attached? %>
        <%= cl_image_tag current_user.avatar.key, class: "avatar-friend" %>
      <% else %>
        <%= image_tag "http://placehold.it/30x30", class: "avatar-friend", alt: "alttext" %>
      <% end %>
<%
=end %>


    <div class="container-friendship">
      <div class="row mb-3">
        <% @friendships.each do |friendship| %>
          <div class=" col-4 friendship text-center mt-2">
            <%= link_to toggle_favorite_friendship_path(friendship) do %>
              <%= cl_image_tag friendship.friend.avatar.key, class: 'avatar-profile' %>
              <p>
                <%= friendship.friend.first_name %>
              </p>
              <% if friendship.favorite? %>
                <i class="fas fa-star text-linear-gradient" id="favorite-star"></i>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <%#= link_to "Search friends", users_list_path, class: "button-next" %>
    <%#= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn-delete-grey" %>
  </div>

  <%= link_to "Search friends", users_list_path, class: "button-next mb-2" %>

  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "button-next btn-delete-grey mb-2" %>

</div>

app/views/pages/home.html.erb
<div class="map-container position-relative">
  <div class="background-shadow position-absolute"></div>
  <div id="pong-title" class="position-absolute">
    <h1>PONG</h1>
  </div>
  <div class="notifications_center">
    <%= link_to "" , notifications_center_path, id: "link"%>
      <div class="notifications_icon display" 
      data-controller="counter" 
      data-counter-url-value="/"  data-counter-refresh-interval-value="2000" style="visibility: hidden">
          <%= @notifications_counter %>
      </div>
  </div>
  <div class="position-absolute button-wrapper">
    <div class="gradient-box">
      <%= link_to "Share my plan" , events_path, method: :post, class: "text-button" %>
    </div>
  </div>

  <div id="map"
      style="width: 100vw; height: 100vh;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/pages/notifications_center.html.erb
<% @pending_friendships.each do |user| %>
  <div  class="container_notif">
    <p class="mt-4"><%= user.first_name %></p><%= user.id %>
    <% if user.avatar.attached? %>
        <%= cl_image_tag user.avatar.key, class: 'avatar-profile' %>
    <% end %>
    <%= link_to 'Accept', friendship_acceptances_path(invitor_id: user.id), method: :post, class: "button-medium" %>
  </div>
<%end%>

<% @pending_events.each do |event| %>
  <div  class="container_notif">
    <%= cl_image_tag event.user.avatar.key, class: 'avatar-small' %>
    <%= event.user.first_name %>
    <%= event.emoji %>
    <%= link_to "Join 👊", confirm_event_user_path(event.event_users.find_by(user: current_user)) %>
    <%= link_to "Plouf 💦", decline_event_user_path(event.event_users.find_by(user: current_user)), data: { confirm: "Are you sure to decline the event?" } %>
  </div>
<%end%>

app/views/pages/users_list.html.erb
<div class="content-container">
  <div class="pages-title">
    <div class="d-flex align-items-center justify-content-center">
      <div class="back-button-title">
        <%= link_to dashboard_path do %>
          <i class="fas fa-chevron-left text-white"></i>
        <% end %>
      </div>

      <div class="box-title">
        <h1>Users of Pong</h1>
      </div>

      <div class="empty-box-title"></div>
    </div>

    <p>Find friends, lovers (perhaps), folks you want to see more or people you've just met!</p>
  </div>

  <% @users.each do |user| %>
    <p class="mt-4"><%= user.first_name %></p><%= user.id %>
    <% if user.avatar.attached? %>
      <%= cl_image_tag user.avatar.key, class: 'avatar-profile' %>
    <% end %>

    <% if current_user.get_friendship(user)&.status == 'pending' %>
      <% if current_user.get_friendship(user).friend == current_user %>
        <%#= link_to 'Accept', '' %>
        <%# A FAIRE: CODER LA METHODE ACCEPT POUR CHANGER LE STATUT EN CONFIRMED %>
        <%#= link_to 'Accept', '', friendship_acceptances_path(current_user.get_friendship(user)) %>
        <%= link_to 'Accept', friendship_acceptances_path(invitor_id: user.id), method: :post, class: "button-medium" %>
      <% else %>
        <div class= "btn-delete-grey">
          <p>pending</p>
        </div>
      <% end %>

    <% elsif current_user.get_friendship(user)&.status == 'approved' %>
    <div class= "btn-delete-grey">
        <p>approved</p>
      </div>

    <% elsif current_user.get_friendship(user).nil? %>
      <%= link_to 'Add Friend', friendships_path(params: { friend_id: user.id }), method: :post, class: "button-medium" %>
    <% end %>

    <%# elsif current_user.get_friendship(user)&.status == 'confirmed' %>
    <%# elsif current_user.get_friendship(user)&.status == 'declined' %>

    <%# unless current_user.is_friend?(user) || current_user.get_friendship(user)&.status == 'pending' || current_user.get_friendship(user)&.status == 'confirmed'  %>
    <%# if  %>
      <%#= link_to 'Add Friend', friendships_path(params: { friend_id: user.id }), method: :post, class: "button-medium" %>
    <%# end %>
  <% end %>
</div>